[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[global]
dataFrameSerialization = "legacy"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
